### ISSUE TITLE
[FEAT] Disk I/O (throughput)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#10]
Do you think you could add a disk I/O graph(s) keep in mind i really do not want all my drives on the same graph overlapping (i have 4 drives + 2 hot swap bays installed )
also please support nvme drives not just sata like every every other thing out there (for example not even dolphin shows nvme drives in a live session and you have to mount them via cli)
```
$ ls -l /dev/disk/by-id
total 0
lrwxrwxrwx 1 root root  9 Nov 26 16:13 ata-Corsair_Nova_2_SSD_12036509000013450523 -> ../../sdb
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-Corsair_Nova_2_SSD_12036509000013450523-part1 -> ../../sdb1
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-Corsair_Nova_2_SSD_12036509000013450523-part2 -> ../../sdb2
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-Corsair_Nova_2_SSD_12036509000013450523-part3 -> ../../sdb3
lrwxrwxrwx 1 root root  9 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F3953810 -> ../../sda
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F3953810-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F3953810-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F7SESJYT -> ../../sde
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F7SESJYT-part1 -> ../../sde1
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F7SESJYT-part2 -> ../../sde2
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F7SESJYT-part3 -> ../../sde3
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD10EZEX-21M2NA0_WCC3F7SESJYT-part4 -> ../../sde4
lrwxrwxrwx 1 root root  9 Nov 26 16:13 ata-WDC_WD5000AAKX-001CA0_WD-WCAYUY966338 -> ../../sdf
lrwxrwxrwx 1 root root 10 Nov 26 16:13 ata-WDC_WD5000AAKX-001CA0_WD-WCAYUY966338-part1 -> ../../sdf1
lrwxrwxrwx 1 root root 10 Nov 26 17:03 ata-WDC_WD5000AAKX-001CA0_WD-WCAYUY966338-part2 -> ../../sdf2
lrwxrwxrwx 1 root root 10 Nov 26 20:58 ata-WDC_WD5000AAKX-001CA0_WD-WCAYUY966338-part3 -> ../../sdf3
lrwxrwxrwx 1 root root 13 Nov 26 16:13 nvme-Force_MP500_18107956000123380298 -> ../../nvme0n1
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-Force_MP500_18107956000123380298-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-Force_MP500_18107956000123380298-part2 -> ../../nvme0n1p2
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-Force_MP500_18107956000123380298-part3 -> ../../nvme0n1p3
lrwxrwxrwx 1 root root 13 Nov 26 16:13 nvme-nvme.1987-3138313037393536303030313233333830323938-466f726365204d50353030-00000001 -> ../../nvme0n1
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-nvme.1987-3138313037393536303030313233333830323938-466f726365204d50353030-00000001-part1 -> ../../nvme0n1p1
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-nvme.1987-3138313037393536303030313233333830323938-466f726365204d50353030-00000001-part2 -> ../../nvme0n1p2
lrwxrwxrwx 1 root root 15 Nov 26 16:13 nvme-nvme.1987-3138313037393536303030313233333830323938-466f726365204d50353030-00000001-part3 -> ../../nvme0n1p3
lrwxrwxrwx 1 root root  9 Nov 26 16:13 usb-Samsung_Flash_Drive_0376119040006787-0:0 -> ../../sdc
lrwxrwxrwx 1 root root 10 Nov 26 16:13 usb-Samsung_Flash_Drive_0376119040006787-0:0-part1 -> ../../sdc1
lrwxrwxrwx 1 root root  9 Nov 26 16:13 usb-TS-RDF5_SD_Transcend_000000000039-0:0 -> ../../sdd
lrwxrwxrwx 1 root root  9 Nov 26 16:13 usb-TSSTcorp_CDDVDW_SN-208BB_523848433647494334303134-0:0 -> ../../sr0
lrwxrwxrwx 1 root root  9 Nov 26 16:13 wwn-0x50014ee1aeddf08c -> ../../sdf
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee1aeddf08c-part1 -> ../../sdf1
lrwxrwxrwx 1 root root 10 Nov 26 17:03 wwn-0x50014ee1aeddf08c-part2 -> ../../sdf2
lrwxrwxrwx 1 root root 10 Nov 26 20:58 wwn-0x50014ee1aeddf08c-part3 -> ../../sdf3
lrwxrwxrwx 1 root root  9 Nov 26 16:13 wwn-0x50014ee261bd3eed -> ../../sde
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee261bd3eed-part1 -> ../../sde1
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee261bd3eed-part2 -> ../../sde2
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee261bd3eed-part3 -> ../../sde3
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee261bd3eed-part4 -> ../../sde4
lrwxrwxrwx 1 root root  9 Nov 26 16:13 wwn-0x50014ee2b4bd7e8c -> ../../sda
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee2b4bd7e8c-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Nov 26 16:13 wwn-0x50014ee2b4bd7e8c-part2 -> ../../sda2
```

I really hope swap layers on top of ram so i see it when i eventually have a mem leak with 14GB ram + 8GB swap and i notice it getting slow i can see why at a glance

and yes my /etc/fstab file is a bit complex to say the least

**Comment by ForteDexe** [comment]
hmm, my dolphin on manajaro kde can see and mount nvme via GUI
but ye, I would love to have disk i/o text/graph too, I have 6 drives

**Comment by GM-Script-Writer-62850** [comment]
Where do they show up? i have never seen my nvme partitions show up in dolphin, the drive is connected to the CPU not the chipset if that matters

**Comment by orblazer** [comment]
Hello,
For this feature you think to have dynamic graph like 1 graph by disk for Read/Write ?
If is yes, that look like complicated to implement because if we don't want dynamic maximum value we need dynamic settings (1 settings line by each disk).

**Comment by GM-Script-Writer-62850** [comment]
i am good with user defined, though some common speed would be good to have in a select menu like 80,120,150,200,300,600,3000,6000,12000
80/120/150/200 are typical for HDDs, 300/600 for typical SSD and 3000+ is for NVME SSDs (12k is for pcie 5 drives, server products at this time)

i would very much like my disk to not be combined into one graph, if they were you would be lucky to see activity on a HDD if you have a fast NVME with the speed difference, let alone a useful idea as to the I/O rate by looking at the graph showing under 1% usage

**Comment by orblazer** [comment]
I have check in sensors if that is possible but i can't automatically retrieve data of psychical drive but only of each partitions :disappointed: 

So to make this i need to make an big work to list partitions if each physical drive and aggregate they values, like i have make for network.

**Comment by GM-Script-Writer-62850** [comment]
this is something else to think about on the UI side of this, maybe there should be a way to set the width and history amount independently from the CPU/RAM/NIC data, so i am thinking like this would be a good idea
```
Hist.length=150 // graph amount
Hist.width=150 // graph width
IO.hist.enabled=true // toggle same as CPU/RAM/NIC
IO.hist.length=50 // I/O graph amount
IO.hist.width=50 // I/O graph width
````
would render like this
CPU@150|RAM@150|NIC@150|nvme0@50|sda@50|sdb@50|sdb@50

or you can screws that you can use 2 instances and do the same thing as is

**Comment by ForteDexe** [comment]
I think you can make it simple at first (1 graph per partition), then if you have time, you can make it like what you did with network i/o
An option to add how many and which partitions we want to display
@GM-Script-Writer-62850 dolphin on kde manjaro lists nvme at Devices, together with hdd and sdd, it just works right out of the box.
