### ISSUE TITLE
[FEAT] choose task/system manager (for click action)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#12]
Before the latest update it opened ksysguard not it open the default system monitor, if i could chose what it opens that would be great, maybe someone would want htop or s-tui

**Comment by GM-Script-Writer-62850** [comment]
Thanks, i think you could polish it with a notice if the application is not found, but meh not a big deal

**Comment by orblazer** [comment]
Hum, i don't know how i can do that.

**Comment by GM-Script-Writer-62850** [comment]
BTW does it support `/usr/local/share/applications` and `~/.local/share/applications`

**Comment by GM-Script-Writer-62850** [comment]
New search field for this is broken

plasmawindowed org.kde.resourcesMonitor-fork
right click -> config -> click action -> search for htop  (enter) -> crash
no output in terminal
not set to htop
list is not filtered
