### ISSUE TITLE
[BUG] install/update broken

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#14]
Discover says the data data is broken...
![Screenshot_20211205_143036](https://user-images.githubusercontent.com/564653/144760816-acbc54b2-f53b-42c3-9a2f-50d67441d51c.png)

You are probably starting to hate me... but this thing is soo much better than a week ago

**Comment by orblazer** [comment]
oh, shit i have fail my release 🤦
