### ISSUE TITLE
[BUG] allocated memory checkbox is glitchy (screen capture)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#15]
[2021-12-05 15-01-39.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7656740/2021-12-05.15-01-39.zip)

I have no idea how to describe this clearly, so here is a screen recording

this is the only checkbox that acts up
manual install of 2.5.2.hotgfix.1

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-051600rc3-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series
```

**Comment by orblazer** [comment]
That is strange, i don't have this issue :confused: 

Could you try to clone the repo and check if that fix the issue ?

**Comment by GM-Script-Writer-62850** [comment]
i think 5a9718d fixed it

**Comment by orblazer** [comment]
Ok so i can close that issue right ?

**Comment by GM-Script-Writer-62850** [comment]
no, cause i am gonna do it with this comment
