### ISSUE TITLE
[BUG] resource monitor does not show values on fedora35

### ISSUE THREAD

**Issue by slartibart70** [orblazer/plasma-applet-resources-monitor#18]
Hi,
here's the bugreport(s) you asked me to put here... :-)

I am using RM(f) successfully on fedora34, latest plasma updates (5.23.4) - and i love it!
I now installed the same thing on a new fc35 installation.
First Problem:
- the values of cpu/ram/network are not shown

This is independent of placing the RMf on the desktop or in the taskbar. I always have values of zero (see screenshot)
Am i missing some libraries?

- placing the RMf into the taskbar now (5.23.4) resizes properly, but i have strange effects if i logoff and re-login into plasma:
the RMf is still where it used to be (left hand side of the statuswidgets in taskbar, but also (and in a much too big size) neighboring the right hand side of the clock.

This happens in X11 and in wayland sessions
(see screenshot)

Any idea how to fix this?

```
Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.7-200.fc35.x86_64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-6600U CPU @ 2.60GHz
Memory: 19.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520
```

- only zero values
 
![Screenshot_20211212_110203](https://user-images.githubusercontent.com/10506408/145708710-544adcf6-b5f4-4a0e-b8aa-251a44c155b0.png)

- double placement and improper size

![Screenshot_20211212_110252](https://user-images.githubusercontent.com/10506408/145708723-5d3eaf0e-baef-49eb-a39b-9813d530bb43.png)

**Comment by slartibart70** [comment]
am i assuming correctly, that you don't know exactly what you forked from? :-)
Still nice to have the network monitor integrated, but worrysome that you don't know the dependencies of the widget?

I found on the solution: it depends on ksysguard
so, with fc35, ksysguard does not seem to be 'default' any more, and hence the plugin just shows zero values.
Install it, and it works.
At least you could update this information on the plasma-store webpage for others to fix similar problems.

Still... the placement problem.
now that it finally worked, i played with the placement much more, and (after several adding/removing/logout-login/etc) i found a working configuration which stays put in the taskbar.

Maybe the kwinrc (or other file, did not check) has faulty entries which are not cleaned up properly when removing/moving/... the widget?
Could be plasma's fault not yours.
Maybe you could still look after it

sorry for the harsh comment, but even if widgets are only small (but very nice looking and useful programs as in the case of your fork) they would improve vastly with a proper documentation.

**Comment by orblazer** [comment]
Hello,
I have see in other issue #8 but i need time to find an way for make that without `ksysguard`.

For the documentation what do you mean exactly ?

**Comment by slartibart70** [comment]
Well, for starters I think the collection of plasma widgets has some problems in itself, because it's very hard for others to find a maintained and useful widget (and not only a shiny toy)
I think it could really help to brag much more about what you did here. Refined the graphics, added the functionality of a different and less capable other widget into your much better one.
And what dependencies it has (e.g.for the time being, ksysguard)
And possibly a prominent link to your github account, so that discussions won't start in the store but in the issue tracker.
And maybe a prominent explanation of the capabilities as readme.md 

Sorry again for my criticism, hope you can accept that.
I myself spent quite a while to figure out what differences I had between fc34 and fc35 and why that damn thing I had working in fc34 would not do so in a fresh fc35 installation.
Google is your friend, but I did not stumble upon #8 where someone else had the same problem.
So this is the thing - you did well in your widget but it may lack acceptance quickly by minor obstacles (if you look in retrospective)
I really would like to see this widget being included in the widget set of plasma, their default widgets don't work as smoothly in the taskbar (and I don't want to clean away windows just to peek at the desktop to see what the machine is doing...)

I think this can only be achieved by more and better advertising and, for example, a rename without the fork suffix 😁
Anyway... Glad to hear you have more ideas to implement! (And thanks for your time doing so)

**Comment by orblazer** [comment]
Thanks for your advice i will improve the doc, and i'm open for an new name ;)
