### ISSUE TITLE
[BUG] History wiped when configuring widgets

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#19]
**Describe the bug**
History gets cleared when i right click on a places, doityourselfbar, system monitor, system monitor (fork) widget and click configure

**To Reproduce**

Right click applet -> configure applet/widget
thus far i only found this can be trigged with
doityourselfbar
system monitor
system monitor (fork)
places

**Expected behavior**
history does not just go poof when i open the config window for applets

**Screenshots**
Screen Capture: [2021-12-18 13-27-27.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7739752/2021-12-18.13-27-27.zip)

**Versions (please complete the following information):**

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-051600rc5-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series
**Additional context**

system monitor (fork): 2.5.2-hotfix.1
yea if i could just copy/paste that from the about page...

**Comment by orblazer** [comment]
Wow, that is really weird bug

**Comment by GM-Script-Writer-62850** [comment]
guess that was easy let me find another one real quick like
