### ISSUE TITLE
[BUG] Hover hints do not persist after a data update during hover

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#20]
**Describe the bug**
When you mouse over the widget it switches the info to a label of what is there, but it gets changed back every time the data in the widget gets updated

**To Reproduce**
Hold mouse over widget during update with it set to show tips on hover

**Expected behavior**
mouse hover is respected during update

**Other thought**
It would be cool if it showed the usage of where the cursor was on the graph (same behavior as the GPU-Z sensors tab)

**Screencapture**
[2021-12-19 10-48-27.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7741096/2021-12-19.10-48-27.zip)

https://i.imgur.com/dN9uwXf.png

**Versions (please complete the following information):**

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-051600rc5-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series

plasma-applet-resources-monitor (fork): 2.5.3-hotfix.1 (be nice if the widget allowed highlighting for copy/paste)

**Comment by orblazer** [comment]
That is an mistake :sweat_smile:

I go deploy that fix in couple of hours (just for make sure i doesn't have another bug).
