### ISSUE TITLE
[BUG] Memory graph in bytes is always at the bottom

### ISSUE THREAD

**Issue by TiGR** [orblazer/plasma-applet-resources-monitor#26]
When you deselect option to show memory in percentage, the memory usage is at zero:

![image](https://user-images.githubusercontent.com/281226/148520850-58e4ba42-4568-4d41-b6d5-d189e05a6619.png)

And now, enabling showing memory in percentage, at the same moment:

![image](https://user-images.githubusercontent.com/281226/148520973-ad7ac0e2-050c-4c42-8a5c-08d975c8d37e.png)

1. Go to widget settings 
2. Uncheck "Memory in percentage"
3. See the error

The graph should be the same, only the number displayed should be different.

- Version : 2.6.3
- KDE Plasma Version : 5.23.5
- KDE Frameworks Version : 5.89.0
- Qt Version : 5.15.3
- Kernel Version : 5.11.0-44-generic
- OS Type : KDE Neon
- Graphics Platform : X11

**Comment by orblazer** [comment]
Hello,
I cant reproduce that issue.

Could you debug some value ?

Step for debug :
1. Clone this repo
2. Add `print(ramGraph.maxMemory)` after this line https://github.com/orblazer/plasma-applet-resources-monitor/blob/4cc431f94620058e87f5323ee719090964a276f4/package/contents/ui/main.qml#L195
3. Run the dev env by run `npm run dev` or `./scripts/dev.sh`

Thanks

**Comment by TiGR** [comment]
Just in case, I have no swap, and the settings look like this:

![image](https://user-images.githubusercontent.com/281226/148536979-ea04bdc2-307b-40f0-a573-43588409c0c2.png)

I'll test it later, as you describe.

**Comment by orblazer** [comment]
Oh ok, you don't neep to reproduce without swap i have the issue.
