### ISSUE TITLE
[FEAT] have more options for CPU and RAM graphs

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#28]
**Describe the bug**
CPU usage looks to include I/O wait time as copying files shows over 50% usage while top shows well under 10%

**To Reproduce**

1. Copy a large volume of files from 1 HDD to another HDD (not high speed SSD)
2. Look at applet shows massive CPU usage

**Expected behavior**

Shows actual CPU usage not operation wait time as usage

**Screenshots**

![Screenshot_20220122_174204](https://user-images.githubusercontent.com/564653/150657728-a98429fd-45b2-4a96-9e3e-f318d09fd44c.png)

**Versions (please complete the following information):**
Applet version: 2.7.1

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.23.90
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.2-051602-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Additional context**

**Comment by orblazer** [comment]
Hello,
That look like not an real bug but an improvement to allow exclude `wait usage` because vent in `system monitor` that usage is included in total CPU usage.

**Comment by GM-Script-Writer-62850** [comment]
There is something similar going on with ram usage
![Screenshot_20220123_080809](https://user-images.githubusercontent.com/564653/150680129-37022c99-ccdd-43b5-8882-70cbf97054a6.png)

**Comment by orblazer** [comment]
Hum, i can add options for that too 

And in you pictures for memory you have 3 different values because :
- htop: show `application`
- top/sleep : for used seem to show `allocated`
- system monitor & the widget : show `physical`

Note : with `libksysguard` its look like impossible to have `allocated`, i have only `physical`, `application`, `buffer` and `cache`

**Comment by GM-Script-Writer-62850** [comment]
sleep, what? oh i think i know that you are talking about
`while [ 1 ];do sleep 1;clear;free -h;done`

i would just note that showing allocated is not supported and only physical is supported to label it as physical ram usage eg:
`Show physical memory monitor`

Why are you using monitor/graph interchangeably under charts? probably best to call it a graph or a monitor, i vote for calling them graphs or charts (seems more logical ot me and it is the shorter word)

**Comment by GM-Script-Writer-62850** [comment]
Maybe you can make "[X] Show <select: physical/application/buffer/cache> memory monitor"

**Comment by orblazer** [comment]
Yes that an mistake to call it `monitor`.
For `Show physical memory monitor` this has disappear in 2.6.0 when i have switch to `libksysguard`.

I think i can add an selector like network for choose between `none`, `physical`, `physical in %`, `application` and `application in %`.

And maybe i can make the same behavior for CPU for allow to exclude `wait`.
NOTE: in future i think i should make an way to add and move each chart like the `plasma system monitor` app
