### ISSUE TITLE
[FEAT] Add an options to show memory both as GiB and percentage

### ISSUE THREAD

**Issue by SylEleuth** [orblazer/plasma-applet-resources-monitor#31]
Just as I suggested in title. It would be nice fill that empty space:

![Screenshot_20220225_195802](https://user-images.githubusercontent.com/33354262/155786616-7a9b3d3a-6b49-475f-9a8c-c529b728af8b.png)

**Comment by orblazer** [comment]
Hello,
You still require that feature ? I think i can planned this for `2.10` or `3.0`.

**Comment by SylEleuth** [comment]
I wasn't using swap memory back then. Now I do and it has it's place under ram. What would be better though is to have percent in the same line, e.g. 8GiB (50%).

**Comment by orblazer** [comment]
Hello,
The 3.0 starting to have an roadmap and date due to Plasma 6 release.

Also for that release i need yours advice if you want, on where and how i release it, you just have to answer at the poll here: https://github.com/orblazer/plasma-applet-resources-monitor/discussions/68.

Thanks.

**Comment by orblazer** [comment]
Hello,

I have decide to publish one last feature update for Plasma 5.x with your suggestion !
Check it here : https://github.com/orblazer/plasma-applet-resources-monitor/releases/tag/v2.11.0

Thanks.
