### ISSUE TITLE
[BUG] Network graph not showing data for some devices

### ISSUE THREAD

**Issue by iyanmv** [orblazer/plasma-applet-resources-monitor#32]
**Describe the bug**
Even though I select all network interfaces (see screenshot below), graph don't show any upload/download speed when I'm using the docking station interface (enp82s0u2u4 in this case). It does work when I'm using the wireless interface (wlp0s20f3).

**To Reproduce**
Not sure exactly how to reproduce. In my desktop it works just fine with both wifi and ethernet devices. But in my laptop it fails when I'm using the docking station (connected with Thunderbolt), even though it shows devices correctly in the data tab.

**Expected behavior**
Speeds are shown no matter what device is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/15230534/156326461-4814cea8-8436-4954-b20b-5138f8278896.png)
![image](https://user-images.githubusercontent.com/15230534/156327068-eb66d905-228f-45b4-9928-899020d9965b.png)

**Versions (please complete the following information):**

- Version : 2.7.1
- KDE Plasma Version : 5.24.2
- KDE Frameworks Version : 5.91.0
- Qt Version : 5.15.2+kde+r39-3
- Kernel Version : 5.16.11
- OS Type : Arch Linux 64-bit
- Graphics Platform : X11

**Comment by orblazer** [comment]
Hello,
Sorry for the wait but that look like similar as #23.

And in resume that issue seems to come `libksysguard` (or just they implementation in QML) and the only solution i see is to fix it with C++.

**Comment by orblazer** [comment]
Oh ok, great,
