### ISSUE TITLE
Memory display is not correct on Fedora 36 [BUG]

### ISSUE THREAD

**Issue by liyakun** [orblazer/plasma-applet-resources-monitor#33]
**Describe the bug**
The display of used memory is not correct on Fedora 36

**To Reproduce**
Open `htop` in the terminal and check the difference between `htop` and the shown memory usage from this applet.

![image](https://user-images.githubusercontent.com/7370334/171904797-4f6217e6-b86e-481b-a0f0-57fed21b2a41.png)

**Versions (please complete the following information):**

- Version : 2.7.1
- KDE Plasma Version : 5.24.5
- KDE Frameworks Version : 5.93.0
- Qt Version : 5.15.3
- Kernel Version : 5.17.11-300.fc36.x86_64
- OS Type : Fedora Linux 36
- Graphics Platform : X11

**Comment by liyakun** [comment]
@orblazer the ram usage information is even different with the original software at https://github.com/kotelnik/plasma-applet-resources-monitor

![image](https://user-images.githubusercontent.com/7370334/172044891-7169a76b-8862-4767-a08a-6027d7e0cdf8.png)

The left side is from the original software and the right side is from this repository.

**Comment by orblazer** [comment]
Hello,
This is exactly same issue as #28.
