### ISSUE TITLE
[BUG] Wrong CPU frequency reported

### ISSUE THREAD

**Issue by max0x7ba** [orblazer/plasma-applet-resources-monitor#34]
The applet reports wrong Ryzen 5950X CPU frequency.

`cpupower monitor` and the original Resource Monitor applet report correct CPU frequency.

This applet reports wrong CPU frequency. See the screenshots below.

**To Reproduce**

1. Install the applet.
2. Install the original applet next to it.
3. Run `sudo watch cpupower monitor`.
4. Observe this applet reporting wrong CPU frequency. 

**Expected behavior**
Correct actual CPU frequency is reported.

**Screenshots**
In the first screenshot below, the CPU runs at ~4.05GHz, this applet reports 3.4GHz.

![screenshot](https://i.imgur.com/rIgz5A3.png).

In the second screenshot below, the CPU runs at ~3.6GHz, this applet reports 4.0GHz.

![screenshot2](https://i.imgur.com/9HzdwnF.png)

**Versions**
- Version : 2.7.1
- KDE Plasma Version : 5.25.5
- KDE Frameworks Version : 5.97.0
- Qt Version : 5.15.5
- Kernel Version :  5.15.0-46-lowlatency #49~20.04.1-Ubuntu
- OS Type : KDE Neon 5.25 64-bit
- Graphics Platform : X11

**Comment by orblazer** [comment]
Hello,
This issue seam like to be similar to #28. In `2.8.0` i go to add some option to customize unit of CPU (via 90791d9), so when that version release, i'm open to listen if that fix your issue or if i need to subtract `wait time`to cpu usage.

**Comment by max0x7ba** [comment]
I switched to using KDE Plasma native System Monitor Widget for CPU and GPU clocks and it works flawlessly for me.

![screenshot](https://i.imgur.com/sMAbK4H.png).

**Comment by orblazer** [comment]
Hello, this is fixed by a6f32717b970fa5537f43cc860bde78730ec30ed (v2.8.0) AND is configurable with b3efc0192252581c4ef0007e12b464b2bb329430 (v2.10.0)
