### ISSUE TITLE
[BUG] Unable to configure data, missing tabs

### ISSUE THREAD

**Issue by ctron** [orblazer/plasma-applet-resources-monitor#36]
**Describe the bug**

In the "data" tab, only the "Network" tab is show, all other tabs are gone.

**To Reproduce**

1. Open settings
2. Navigate to "data"

**Expected behavior**

All tabs should be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/202474/206177365-1361e4c3-ac3c-4a58-9248-c338bf4271f3.png)

**Versions (please complete the following information):**

- Version : 2.7.1
- Graphics Platform : X11
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.11-300.fc37.x86_64 (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series

**Additional context**

**Comment by orblazer** [comment]
This is normal, `Network` is only tab in that section.

**Comment by ctron** [comment]
> This is normal, `Network` is only tab in that section.

Hm, maybe I mixed that up with another applet I used in the past. Sorry for the noise.
