### ISSUE TITLE
[BUG] Sleep -> wake up: network monitor show 0 bps 

### ISSUE THREAD

**Issue by pawlosck** [orblazer/plasma-applet-resources-monitor#37]
1. Sleep computer
2. wake up
3. Network monitor doesn't work -> BUG
4. Restart computer
5. Network monitor works correctly

**Comment by orblazer** [comment]
Hello,
I think that issue could bee related to #23.

**Comment by pawlosck** [comment]
Could you try with ethernet card via usb hub?

Last days, I discovered, that problem is connected with ethernet card. When I am using WiFi only(ethernet card disconnected -> not connected to laptop), then widget works correctly.
I am using ethernet card via USB hub.
Laptop -> usb hub -> usb hub with ethernet card, so maybe widget can't detect ethernet card when laptop waking up.

**Comment by orblazer** [comment]
I don't have ethernet or WIFI card so i can't try that.

Before digging on widget debug you can try with `org.kde.plasma-systemmonitor` ("System Monitor" app) by create an new pages, add your sensors et check if that work here.

If the response is "yes"i have 2 theory about the issue :
- the sensors is not present when the computer wake (i don't know if the widget is restarted)
- that could be same issue as #23

And for debugging the app i have provide step in my previous comment.

**Comment by pawlosck** [comment]
I installed version 2.9.0. Currently show "---" for download, upload and for Clock (CPU).
I added new tab for System monitor with download value and it show 0, so probably problem is not connected with widget, but with kde sensors. Is it possible to restart sensors? Maybe some kernel module is not loaded again?

**Comment by pawlosck** [comment]
![obraz](https://user-images.githubusercontent.com/3769853/236570435-7cbffc71-53b3-4fed-adf7-9e160d5dd249.png)

**Comment by pawlosck** [comment]
Currently, after restart laptop, doesn't work too. Widget doesn't show correct values and in system monitor doesn't show correct values. There is problem and I think, problem is connected with KDE.

**Comment by orblazer** [comment]
Yes that problem look to come from https://invent.kde.org/plasma/libksysguard.

I can report the bug if you want and link here.

For the clock issue have exactly same behavior? If is yes I think it's sensors itself.
And for helping them to fix the issues I go to dig if we can get the information from the command.

**Comment by pawlosck** [comment]
Yes, please report a bug. I hope it will solve problems.
For the clock, problem can be related to widget, because system monitor show correct value.

![obraz](https://user-images.githubusercontent.com/3769853/236580292-90e518b2-fa4f-4eca-bbca-fad674fe9acd.png)

**Comment by orblazer** [comment]
> Yes, please report a bug. I hope it will solve problems. For the clock, problem can be related to widget, because system monitor show correct value.
> 
> ![obraz](https://user-images.githubusercontent.com/3769853/236580292-90e518b2-fa4f-4eca-bbca-fad674fe9acd.png)

Could you try this :
- Use `CPU > All > Averaage CPU Frequency` sensors (that is what i use in widget)
- Enable "CPU temperature" AND add `CPU > All Average CPU Temperature` in Sytem Monitor (for double check)

If both step works that look wierd, but if is not i think could be related to same issue.

**Comment by pawlosck** [comment]
> - Widget Version :  2.9.0
> - KDE Plasma Version :  5.24.7
> - KDE Frameworks Version :  5.98
> - Qt Version :  5.15.3
> - Kernel Version :  Linux CK 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> - OS Type :  64

Sorry for long break, but I was too busy to write any message.

**Comment by pawlosck** [comment]
> i will point out i am NOT able to reproduce this, i am using a intel LAN PICe card
> 
> maybe something is going on with the device waking up and it not showing up for a second during wake up?

Probably you are right, because, sometimes usb ethernet card is not detected. I don't know why. Maybe you could add button to refresh all network cards. Maybe it should solve problem.

**Comment by orblazer** [comment]
> EDIT: Ethernet card is not displayed in network widget in systray. I see only network card from docker and wlan card (when enabled).

@pawlosck Ok so with that said, this look issue from your side and not FROM widget.

> Probably you are right, because, sometimes usb ethernet card is not detected. I don't know why. Maybe you could add button to refresh all network cards. Maybe it should solve problem.

I wont add an feature like that because is not the objective of the widget, i only read the data and i don't modify it.
