### ISSUE TITLE
[FEAT] Option to remove background when using widget on desktop

### ISSUE THREAD

**Issue by V-tin** [orblazer/plasma-applet-resources-monitor#38]
**Describe the solution you'd like**
It would be nice to have an option to remove background when using widget on desktop.

![Screenshot_20230428_134105](https://user-images.githubusercontent.com/93987650/235128148-9a307ab8-ebcb-4046-b2c1-2339bd293cde.png)

**Comment by orblazer** [comment]
Hello,
I have search to find an solution, but this seam like come directly from Plasma and i don't have the hand on it.
