### ISSUE TITLE
[BUG] Numbers often don't fit the widgets graph

### ISSUE THREAD

**Issue by lodriguez** [orblazer/plasma-applet-resources-monitor#4]
Network traffic in particular often exceeds the graph. Maybe remove the decimal place for 10+MB/s
![Screenshot](https://user-images.githubusercontent.com/5723119/131094639-f6d54e00-0089-417c-b45a-a0519c15fed1.png)

**Comment by orblazer** [comment]
I think its not an good idea but i can add more space between each charts
