### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ninja85a** [orblazer/plasma-applet-resources-monitor#41]
**Describe the bug**

I cant apply when I enable show temperature, disk I/O monitor and all GPU monitor options, even applying by changing the update interval doesnt apply any of those settings 
**To Reproduce**

1. Go to the settings
2. enable any of the extra options for CPU, GPU monitor and disk I/O monitor
3. not see apply button light up

**Expected behavior**

to be able to apply the options and see them applied
**Screenshots**

**Versions (please complete the following information):**

- Version : 2.7.1
- KDE Plasma Version : 5.27.4
- KDE Frameworks Version : 5.105.0
- Qt Version : 5.15.9
- Kernel Version : 6.2.12-200.fc37.x86_64 
- OS Type : 64bit fedora 37
- Graphics Platform : wayland

**Comment by orblazer** [comment]
Hello,
Have you reboot plasma for refresh widget after update it ?
It's common issue.

**Comment by ninja85a** [comment]
I'll try that when I get home

-------- Original Message --------

**Comment by ninja85a** [comment]
yup that got it working, thanks
