### ISSUE TITLE
[BUG] "General" settings is empty

### ISSUE THREAD

**Issue by lubomir-moric** [orblazer/plasma-applet-resources-monitor#43]
**Describe the bug**
After last update, "General" settings page is empty.

**To Reproduce**
Open plasmoid settings.

**Expected behavior**
"General" settings page is showing settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/10599985/235338811-5b568afc-a38f-4d5b-8969-c7bf8a93e8a3.png)

**Versions (please complete the following information):**

- Version : 2.8.0-hotfix1
- KDE Plasma Version : 5.24.4
- KDE Frameworks Version : 5.90.0
- Qt Version : 5.15.2
- Kernel Version : 5.14.21-150400.24.60-default (64-bit)
- OS Type : openSUSE 15.4
- Graphics Platform : X11

**Comment by orblazer** [comment]
Hello,
That probably due to bump `org.kde.plasma.components` to 3.0, but in github repo that version was implement in 2017.

So could you share the log by running `journalctl /usr/bin/plasmashell -e` OR by running in isolated environment with `plasmawindowed org.kde.resourcesMonitor-fork` (for `plasmawindowed` you can put logs in file with adding `&> file` at the end) ?

Thanks.

**Comment by lubomir-moric** [comment]
Hello, here are the logs using `plasmawindowed org.kde.resourcesMonitor-fork`:
Starting app:

```kf.plasma.quick: Applet preload policy set to 1
kf.plasma.core: requesting config for "Resources Monitor (fork)" without a containment!
Using KRun from QML is deprecated (since 5.88). Use Qt.openUrlExternally, or the KIO::OpenUrlJob/KIO::ApplicationLauncherJob classes from C++ instead.
qml: 0
```

Opening settings:
```file:///home/leeon/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/config/ConfigGeneral.qml:439:36: PlasmaExtras.Highlight is not a type
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:59: TypeError: Cannot read property 'cfg_objectNameChanged' of null
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:46: TypeError: Cannot read property 'implicitHeight' of null
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:190:17: QML ConfigCategoryDelegate: Binding loop detected for property "implicitHeight"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:46: TypeError: Cannot read property 'implicitHeight' of null
```

Exiting the app:
```file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:22: TypeError: Cannot read property 'cfg_objectName' of null
<Unknown File>:1: TypeError: Cannot read property 'Layout' of null
QObject::disconnect: Unexpected nullptr parameter
```

**Comment by orblazer** [comment]
Could you try if other pages work or not ? Is for know what i need to revert. Thanks.

**Comment by lubomir-moric** [comment]
Other sections work:
![image](https://user-images.githubusercontent.com/10599985/235420974-57c4dd71-22df-4560-ac99-1d933b59df95.png)
![image](https://user-images.githubusercontent.com/10599985/235421012-16d0a29f-7944-4581-b91a-8e40be4eb0f2.png)
![image](https://user-images.githubusercontent.com/10599985/235421050-0a6a7d56-2ac7-4f12-95a4-de28cdb18be1.png)

**Comment by orblazer** [comment]
I go to implement deprecated `PlasmaComponents2.Highlight` but in future framework releases the support for `PlasmaComponents 2.0` will drop so `PlasmaComponents2.Highlight` too.

So in version `2.10` of my widget i go to drop that support too.
