### ISSUE TITLE
[BUG] old setting break it

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#44]
**Describe the bug**
![Screenshot_20230501_103855](https://user-images.githubusercontent.com/564653/235469065-5db5d7ef-59f3-437d-90e9-21bbc1d915a0.png)

**To Reproduce**

1.update to new version from old version (from last release to current release)
2. open setting to try awesome new stuff !
**3. forget where setting are saved to...**

**Expected behavior**
setting are reset or converted

**Screenshots**

**Versions (please complete the following information):**

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.13-051713-generic (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

**Additional context**

**Comment by orblazer** [comment]
This is duplicate to #43.
