### ISSUE TITLE
applet not visible anymore with new update

### ISSUE THREAD

**Issue by zontafil** [orblazer/plasma-applet-resources-monitor#46]
**Describe the bug**
Hello,
I've just updated to the new version. The applet was working correctly for a few minutes, now it's completely invisible.

I can see it's loaded, I can right click and enter the settings correctly, but no matter which settings I use, the applet still doesn't show anything

Is there something I can do, or some debug log I can see?

Version is 2.9.0

**Versions (please complete the following information):**

- Version : 2.9.0
- KDE Plasma Version : 5.24.7
- KDE Frameworks Version : 5.92.0
- Qt Version : 5.15.3
- Kernel Version : 5.19.9.0-41-generic
- OS Type : 64bit ubuntu 22.04
- Graphics Platform : X11

**Comment by orblazer** [comment]
Hello,
Have you try to restart plasma or logout/login for restart completely the widget ?

If you have done that, could you check the log with `journalctl /usr/bin/plasmashell -e` OR by running in isolated environment with `plasmawindowed org.kde.resourcesMonitor-fork` ?

Thanks.

**Comment by zontafil** [comment]
I've tried both way, and got the same log:
``` % plasmawindowed org.kde.resourcesMonitor-fork                   
kf.plasma.quick: Applet preload policy set to 1
kf.plasma.core: requesting config for "Resources Monitor (fork)" without a containment!
Using KRun from QML is deprecated (since 5.88). Use Qt.openUrlExternally, or the KIO::OpenUrlJob/KIO::ApplicationLauncherJob classes from C++ instead.
file:///home/fzonta/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:61: TypeError: Cannot read property 'updateInterval' of undefined
file:///home/fzonta/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:42: TypeError: Cannot read property 'length' of undefined
file:///home/fzonta/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:85: TypeError: Cannot read property 'graphOrders' of undefined
qml: 0
file:///home/fzonta/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:42: TypeError: Cannot read property 'length' of undefined
```
note that normally I don't get the `kf.plasma.core: requesting config for "Resources Monitor (fork)" without a containment!` warning when run in the panel, but I still get the same error

**Comment by orblazer** [comment]
Ok, that is due to your old framework version.

I have revert my change so should be fixed in `2.9.1` but that is temporary because in `3.0` i go to drop old versions to use PlasmaComponents3.

**Comment by zontafil** [comment]
Alright, thanks. I'll keep in mind that

**Comment by GM-Script-Writer-62850** [comment]
would this be related?

![Screenshot_20230505_233717](https://user-images.githubusercontent.com/564653/236597182-c6104c0e-8acc-4afa-9ef1-f5400e2a1b5d.png)

**Comment by orblazer** [comment]
@GM-Script-Writer-62850 if your KDE framework version is before `5.94.x` definitively yes.
