### ISSUE TITLE
[FEAT] Separate different physical disk drives or maybe put them in groups

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#49]
**Is your feature request related to a problem? Please describe.**
Currently all desk are shoved into a single graph...
i have 4 drives installed (and room for more) and the performance scaling of a NVME SSD is going to make it hard to notice HDD activity in the same chart

max drive transfer speed should be on a per drive bases, a HDD may be able to do 160 MB/s while a sata SSD can do 580MB/s or a NVME SSD can do 2.9GB/s

**Describe the solution you'd like**
Separate charts for each drive and or separate colors for each drive

**Comment by orblazer** [comment]
Hello,
The 3.0 starting to have an roadmap and date due to Plasma 6 release.

Also for that release i need yours advice if you want, on where and how i release it, you just have to answer at the poll here: https://github.com/orblazer/plasma-applet-resources-monitor/discussions/68.

Thanks.

**Comment by orblazer** [comment]
For that i have think of 2 options :
1. Use stacked graph like ram, GPU and network. But that limit labels to only aggregated values (average, sum, max) AND graph to "usage" only (not R/W except if we limit number of disk to 2, due to chart size and colors seems to be hard to read)
2. Use 1 graph per disk (like i think for supporting multi GPUs)

Tell me what you think about that.

**Comment by GM-Script-Writer-62850** [comment]
1 per disk graph (note that is should not be all or 1, user can select what disk to show)

**Comment by GM-Script-Writer-62850** [comment]
well that was quite the large patch

by chance does this patch work on plasma 5.27, maybe there is a ppa for kubuntu 24.04 for plasma 6...

**Comment by orblazer** [comment]
Hello,
sorry but i have freeze the feature on plasma 5.27, but if some one want port the change to it i'm open to make an new release.

Unfortunately i haven't time to done that in short period.
