### ISSUE TITLE
[FEAT] Make history graphs optional

### ISSUE THREAD

**Issue by mikdeb** [orblazer/plasma-applet-resources-monitor#56]
### Describe the solution you'd like

Make history graphs optional

**Comment by orblazer** [comment]
Hello,
Could you be more precise of what you want ?

If i have understand right, you what hide graphs but still have value ?

**Comment by mikdeb** [comment]
Yes. I guess not everyone needs the graphs and might prefer to have only the numerical values visible.
Maybe a toggle like "show history graphs" might be doable?

I very much appreciate the compact design of your widget that covers all my monitoring needs in one compact space.
Thank you!

**Comment by wokawoka** [comment]
> 

I agree, being able to disable the graphs would be very useful in some cases
thank you

**Comment by orblazer** [comment]
Hello,
The 3.0 starting to have an roadmap and date due to Plasma 6 release.

Also for that release i need yours advice if you want, on where and how i release it, you just have to answer at the poll here: https://github.com/orblazer/plasma-applet-resources-monitor/discussions/68.

Thanks.

**Comment by orblazer** [comment]
Hello,

I have decide to publish one last feature update for Plasma 5.x with your suggestion !
Check it here : https://github.com/orblazer/plasma-applet-resources-monitor/releases/tag/v2.11.0

Thanks.

**Comment by wokawoka** [comment]
Thank you very much for implementing this function!
I still get a line just below the swap usage, though. (see screenshot)
Or is it maybe due to another setting and I could already make it disappear with the actual (2.11.1) version?

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/7824587/bcd359db-7ab3-4530-b311-113ef2437f50)

**Comment by orblazer** [comment]
Hum,
That look like an issue, i will push an patch update for fix it in few hours,

**Comment by wokawoka** [comment]
> Hum, That look like an bug, i will push an patch update for fix it in few hours,

I confirm that the swap red line is no more there.
Thank you so much for your work!
