### ISSUE TITLE
Error loading QML[BUG] 

### ISSUE THREAD

**Issue by msk2000** [orblazer/plasma-applet-resources-monitor#57]
### Current Behavior

I installed the widget and tried to add it to my desktop. All I see is a box with a red sign saying:

"Error loading QML file: file:///home/*******/.local/share/plasma/plasmoids/org.kde.resourcesMonitor-fork/contents/ui/main.qml:68:18: Expected token `;"

### Expected Behavior

There shouldn't be that error and instead system monitoring stuff.

### Steps To Reproduce

**OS:** Ubuntu 18.04, KDE Plasma 5.12.9, QT 5.9.5

Just install and add the widget directly from the desktop as usual.

### Screenshots

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/129243151/223dbed1-b971-4a6b-bf70-70f486ea82a1)

### Logs

```Text
1. ~$ plasmawindowed org.kde.resourceMonitor-fork
Loading default layout
org.kde.plasma: requesting config for "Unknown" without a containment!
```

### Versions

```Markdown
- Widget: IDK how to retrieve that info. It should be the latest as of today. 
- KDE Plasma: 5.12.9
- KDE Framework: 5.44.0
```

**Comment by orblazer** [comment]
Hello,
Sorry but i don't support that old version of KDE. You version is from september 2019 and its out before i have start the project.

Also in next major release (3.x) i go drop versions doesn't support `PlasmaComponents3`.

**Comment by msk2000** [comment]
Thanks for letting me know. @orblazer
