### ISSUE TITLE
Switching to new system monitor app

### ISSUE THREAD

**Issue by david-cortes** [orblazer/plasma-applet-resources-monitor#6]
The `ksysguard` app that this widget uses has been deprecated. Would be helpful to move to the new system activity app so that it would launch something similar to Ctrl+Esc when clicking the widget.

**Comment by orblazer** [comment]
Hello, you have an source of that deprecation ?

**Comment by thegamerhat** [comment]
System managers from other DEs come to mind, but installing them just for one applet will be impractical.

Maybe look over at the [BTop](https://github.com/aristocratos/btop) and their implementation?
