### ISSUE TITLE
[BUG] No GPU info

### ISSUE THREAD

**Issue by SylEleuth** [orblazer/plasma-applet-resources-monitor#61]
### Current Behavior

There is no information for GPU, it shows only ... (three dots).

### Expected Behavior

It should show GPU information.

### Steps To Reproduce

System monitor GPU settings:
```
[Face-93945904362368][Appearance]
chartFace=org.kde.ksysguard.piechart

[Face-93945904362368][SensorColors]
gpu/all/totalVram=244,254,25
gpu/all/usedVram=254,25,128

[Face-93945904362368][Sensors]
highPrioritySensorIds=["gpu/all/usedVram","gpu/all/totalVram"]
totalSensors=["gpu/all/usage"]

[page]
Title=GPU
icon=ksysguardd
loadType=
margin=2

[page][row-0]
Title=
heightMode=balanced
isTitle=false
name=row-0

[page][row-0][column-0]
name=column-0
noMargins=
showBackground=true

[page][row-0][column-0][section-0]
face=Face-93945904362368
isSeparator=false
name=section-0
```
It works there.

### Screenshots

![Screenshot_20230830_135738](https://github.com/orblazer/plasma-applet-resources-monitor/assets/33354262/7f3b221b-8c57-43ad-8c78-38d98f332ec7)

### Logs

```Text
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Plasma Windowed" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Makes the plasmoid stay alive in the Notification Area, even when the window is closed." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Force loading the given shell plugin" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "The applet to open." msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Arguments to pass to the plasmoid." msgid_plural: "" msgctxt: ""
kf.plasma.quick: Applet preload policy set to 1
kf.plasma.core: requesting config for "Resources Monitor (fork)" without a containment!
Using KRun from QML is deprecated (since 5.88). Use Qt.openUrlExternally, or the KIO::OpenUrlJob/KIO::ApplicationLauncherJob classes from C++ instead.
qml: 0
```
New window doesn't show anything except 3 x 3 dots places vertically.

### Versions

```Markdown
- Widget: 2.10.2
- KDE Plasma: 2.27.7
- KDE Framework: 5.109.0
- Qt Version: 5.15.10
- GPU: RADEON RX570
```

### Additional context

It worked without much problems (except https://github.com/orblazer/plasma-applet-resources-monitor/issues/45). I noticed lack of it some time ago, maybe a month ago, but didn't have time to report it so I turned it off. Unfortunately I don't remember when it stopped working.

**Comment by orblazer** [comment]
Hello,
Thanks for reporting.

You have try to select some graphic card in settings and see if that fix it ?

**Comment by SylEleuth** [comment]
> You have try to select some graphic card in settings and see if that fix it ?

What settings You have on mind?

**Comment by orblazer** [comment]
> > You have try to select some graphic card in settings and see if that fix it ?
> 
> What settings You have on mind?

We have an settings at Widget settings > Data > General > Graphic card (at the bottom).

But if you have only one GPU could you select in in `org.kde.plasma-systemmonitor` and share the page with sensor ?

Currently we don't support for `all` GPUs but this could be an feature in 3.0.

**Comment by SylEleuth** [comment]
I missed that option. Turned on and now it works. My bad, it's not a bug.
