### ISSUE TITLE
[FEAT]  plasma 6 support

### ISSUE THREAD

**Issue by bobo123g** [orblazer/plasma-applet-resources-monitor#67]
### Is your feature request related to a problem? Please describe.

I don't know if this is a feature request or if you'd need a whole new fork since there is an API change but I'd love plasma 6 support. I really like this widget and would be willing to donate $50 towards plasma 6 support.

**Comment by orblazer** [comment]
Hello,
Yes that is right type of issues.
And yes that is definitely planned to support plasma 6 for v3.0 (that also includes many refactoring and new features), but I think I will wait for stable release before i starting to work on it.

So for estimate an date i think we can say at least mid March (also depends on Manjaro release for let me fully testing it).

**Comment by orblazer** [comment]
Hello @mehrdadhashira,

I haven't starded the update yet due i'm working on another project, but i think i can start to work on it in few days.
So the date for that release probably moved from mid  March to end of March or during April.

Thanks for the waiting.

**Comment by andrewrembrandt** [comment]
Thank you @orblazer for updating this fantastic widget for Plasma 6 (& for doing the fork in the first place)!

**Comment by orblazer** [comment]
Hello,
I have start an new polls for choose the new name of the widget (for plasma 6) at #71. Please vote !

Thanks.

**Comment by orblazer** [comment]
Hello,
I will give me one last week to finish to check everything and finish to prepare deployment for the Plasma 6 version.
So the release is really close :tada: 

Thanks for you waiting.

**Comment by orblazer** [comment]
The release is now available as first Release Candidate (pre-release) :tada: 

You can download it here :
- KDE store: https://www.pling.com/p/2143899/
- Github: https://github.com/orblazer/plasma-applet-resources-monitor/releases/tag/v3.0.0-rc.1

**Comment by orblazer** [comment]
Hello @antermin, thanks for pointed that, i have remove it.
