### ISSUE TITLE
[FEAT]  Being able to swap upload and download in the network column

### ISSUE THREAD

**Issue by wokawoka** [orblazer/plasma-applet-resources-monitor#69]
### Is your feature request related to a problem? Please describe.

It would be great to be able to  swap the upload and download speed position from above to below and the other way around.
Thank you!

**Comment by wokawoka** [comment]
sorry if I have mixed a feature request with a (potential) bug!

**Comment by orblazer** [comment]
Hello, no problem.
For your issue is same as #23, and long time bug (and i think mainly due to KDE) so that issue would not fix until 3.0.

**Comment by orblazer** [comment]
Hello @wokawoka,
I have move your issue in #23 for keep only feature here.

Thanks.

**Comment by wokawoka** [comment]
> Hello @wokawoka, I have move your issue in #23 for keep only feature here.
> 
> Also can you explain more about which issues this feature can resolve ? I'm a bit confused of the final point for this feature.
> 
> Thanks.

At the moment the network speed indicator lists download speed on top and upload speed on the bottom. Personally, I prefer to see upload speed on the top and download on the bottom.
Being able to configure the order of upload/download (similarly to what [netspeed widget](https://github.com/dfaust/plasma-applet-netspeed-widget allows to do) would be great.
Thank you very much for the great work you are going
