### ISSUE TITLE
[BUG] needs update to kde plasma 6

### ISSUE THREAD

**Issue by CR4CKSTEIN** [orblazer/plasma-applet-resources-monitor#70]
### Current Behavior

needs update to kde plasma 6

### Expected Behavior

needs update to kde plasma 6

### Steps To Reproduce

needs update to kde plasma 6

### Screenshots

needs update to kde plasma 6

### Logs

```Text
needs update to kde plasma 6
```

### Versions

```Markdown
- Widget:
- KDE Plasma:
- KDE Framework:
```

**Comment by orblazer** [comment]
Hello,
This issue already exist here #67, please have sa some research before creating an new issue. Since is already exist, i go to close this.

Thanks.
