### ISSUE TITLE
[Plasma 6] KNOW ISSUES

### ISSUE THREAD

**Issue by orblazer** [orblazer/plasma-applet-resources-monitor#74]
Hello,
This issue list all know issues the widget have.

# Plasma 6

- ~~Could no longer choose application opened when we click because `Kio.KRun` as been removed and no easy way to replace it. So currently if we don't want "Plasma System Monitor", we need write cli command.
  *src: dde668d5a77b6f93666e7586aca88c3426336bac*~~  Fixed with c895723a427fbf9cfb9e5343aaac846b6c86b386

**Comment by datWeazel** [comment]
I already cloned the 3.0 branch and installed the Plasma 6 version to test. If it's ok I would post issues I encounter here.  I'm never developed a plasmoid, so I can't directly contribute (unless I stumble over some obvious stuff :D)   

Issues I encountered so far: 
- Editing the CPU graph, selecting "Disabled" for the second line and enable "Show temperature" will keep the CPU graph from showing any values (only "..." is shown for the CPU graph)

**Comment by orblazer** [comment]
Hello,
Thanks for helping me to develop the widget without "big" bugs :wink: 

That totally right place for your comment, but i think i will mark to "outdated" once the release out.

**Comment by Termuellinator** [comment]
Running `plasma6-applets-resources-monitor-git` from AUR, the widget is displayed with a fixed width (maybe 10px?) on a vertical panel, making it virtually unusable:
![Screenshot_20240329_132838](https://github.com/orblazer/plasma-applet-resources-monitor/assets/22668785/e875c534-7a28-44bd-b2e2-ccdaa5097a36)


Works fine on a horizontal panel.

**Comment by ypnos** [comment]
I'm also trying out the 3.0 branch. I use the plasmoid in a horizontal panel. When I change the Width in Settings/Appearance/Graph to increase it, it does not have any effect. If I then try a smaller amount, the graph width does get smaller. I can then not increase it anymore again. I will get the original width back by restarting Plasma. However, not the desired width as configured.

**Comment by Termuellinator** [comment]
After updating from 2.11.2.r30.gd38d9da-1 -> 2.11.3.r32.g365c541-1, the sizing works much better on vertical panels.
That introduced a different issue though: now the margin is ignored for the width it seems, so the graphs have the same width as the panel and changing the margin only changes the height of the fields.
![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/22668785/e32e67c8-d65e-4d8d-8ca1-f7a2954de992)

**Comment by orblazer** [comment]
> After updating from 2.11.2.r30.gd38d9da-1 -> 2.11.3.r32.g365c541-1, the sizing works much better on vertical panels. That introduced a different issue though: now the margin is ignored for the width it seems, so the graphs have the same width as the panel and changing the margin only changes the height of the fields. The margin is now also ignored when setting height/width manually.

Hello @Termuellinator,
That behavior seem to be identical in Plasma 5 version for me, so i think i didn't understand the issue or that would be an new feature and in that case you should create an feature issue instead and explain more about what at why you want possibility to add margins.
Note the field is currently name "margin" but in reality is simply spacing.

**Comment by Termuellinator** [comment]
I don't really care to much about customizable margins tbh. 
But i think the widget/applet should not be "edge to edge" over the whole width of the panel. It certainly isn't common for other widgets.

That also wasn't the case before (in Plasma 5 and the non-git Version) and even with the size-issue, it at least had a "correct" margin (not sure if the manually set margin took effect there?) on the left (or "outside") edge when setting a width manually.

**Comment by ypnos** [comment]
I made two more observations:

1. My graph's color is set to the "Hightlight" color, which is the default. However I changed my highlight color. Now I still get the old color (blue) in the graph. Even if I switch to some other entry and back to Highlight, it will not change. See screenshot below.
2. I cannot set an update frequency of 0.15 seconds. I can only set 0.1 or 0.2. This might reflect old behavior though.

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/8481470/dc5ed71a-625b-4472-b9e7-ff9f93c93df9)

**Comment by orblazer** [comment]
Hello @ypnos,

> 1. My graph's color is set to the "Hightlight" color, which is the default. However I changed my highlight color. Now I still get the old color (blue) in the graph. Even if I switch to some other entry and back to Highlight, it will not change. See screenshot below.

For applying color you need to click on `Ok` and `Apply`, until that the color wouldn't be applied.

**Comment by Termuellinator** [comment]
With the latest change the width on vertical panels is "back to normal", thank you! :D 
Now the only issue i can find is that the CPU-Temperature only displays `...` for me (5800x3D) - could it be that that is caused by me using zenpower instead of k10temp?

**Comment by orblazer** [comment]
Hello @Termuellinator,
In fact that issue directly come from `ksystemstats` (the package used to provide sensors through `libksysguauard`) and more specificly from that function https://invent.kde.org/plasma/ksystemstats/-/blob/master/plugins/cpu/linuxcpuplugin.cpp?ref_type=heads#L162-L174.

But i think you can create an new bug issue for that to mark it in dedicated issue and i have some question like the reason of you use `zenpower` instead `k10temp`, or some infos for potentially fix it with some syscall. And this is not the ideal place for that.

Thanks.

**Comment by ypnos** [comment]
Hello orblazer,

Thank you for your response, yes I did press the Apply button (you can see it is grayed out in the screenshot), I also swapped to another option, applied, got the expected color, switched back to Highlight, applied, got the blue again although the orange is shown in the dialog.

I believe I also restarted the plasma shell.

Mar 31, 2024 21:21:40 orblazer ***@***.***>:

**Comment by ypnos** [comment]
This is the config:
```
[Containments][45][Applets][86]
immutability=1
plugin=org.kde.resourcesMonitor-fork

[Containments][45][Applets][86][Configuration][Appearance]
customGraphWidth=true
fontScale=32
graphHeight=20
graphMargin=15
graphWidth=100
historyAmount=50

[Containments][45][Applets][86][Configuration][ConfigDialog]
DialogHeight=570
DialogWidth=760

[Containments][45][Applets][86][Configuration][General]
graphs=[{"_v":1,"type":"cpu","colors":["highlightColor","textColor","textColor"],"sensorsType":["usage","classic",false],"clockAgregator":"average","eCoresCount":0,"thresholds":[85,105]}]
updateInterval=0.1
```

I also restarted the plasma-shell and the graph was still blue. Then I changed the color to Background and applied. I changed it back to Highlight and applied. It is blue again.

**Comment by ypnos** [comment]
I just realized that in the Task Manager panel widget, the highlight (current window) is also still blue. So I assume this is a general problem of plasma panels / plasma shell? It's weird that all the dialogs show the correct accent color.

**Comment by orblazer** [comment]
Yes this is definitively not an issue from my widget du to `"colors":["highlightColor"...]` values in you config, so i think your issue is more an theme issuer then KDE. I think if you go in `Colors` settings (Colors & Theme > Colors) you will potentially see the issue here.
Note: for trying to reproduce the issue i have simply change the accent color on that page.
