### ISSUE TITLE
[FEAT] Persistent labels

### ISSUE THREAD

**Issue by larvanitis** [orblazer/plasma-applet-resources-monitor#82]
### Is your feature request related to a problem? Please describe.

When multiple graphs are displayed, it is not clear what each one is.

![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/1144686/6761394d-7736-4902-ac55-1996a6701089)

### Describe the solution you'd like

I'd like to have the ability to set some kind of labeling/legend, which will be visible at all times.

So for example, I'd like the net monitor to be like:

```
↓  42,0 KiB/s
↑ 483,5 KiB/s
```

and the disk monitor like:
```
R  84,0 KiB/s
W   1,0 MiB/s
```

This could be set in the configuration in the same way the colors are (eg "Custom Label", could be empty by default):
![image](https://github.com/orblazer/plasma-applet-resources-monitor/assets/1144686/0f71b9d2-b686-4ab5-904d-2b96f214218b)

Also, it would be awesome if emojis were supported.

_btw I believe "Text displayment" should be "Text display"_

**Comment by orblazer** [comment]
Hello,
Do you think is enough to have only 1 checkbox on network graph and disks graphs like `Show icons (↓ / ↑)` ?
Or you think we need an free text input ?

BTW, the alignement should only go on left or right to text and not aligned like you have mentioned, so the render should be something like :
```
  ↓ 42,0 KiB/s
↑ 483,5 KiB/s
# OR
  42,0 KiB/s ↓
483,5 KiB/s ↑
```
