### ISSUE TITLE
[BUG] Second line of memory is not displayed

### ISSUE THREAD

**Issue by wtklrs** [orblazer/plasma-applet-resources-monitor#89]
OS: Arch linux
DE: Plasma 6.1.0 [KF5 ] [Qt ] (x11)
Widget Version: latest

Preview:
![2024-06-29_01 36 04](https://github.com/orblazer/plasma-applet-resources-monitor/assets/98470141/a6078ad3-e5e3-4a70-8986-ef715be023dc)

Settings:
![2024-06-29_01 37 06](https://github.com/orblazer/plasma-applet-resources-monitor/assets/98470141/fbd9540c-a3d2-4efe-9b4e-b9c1dfc275d0)

`free`:
```bash
                  total        used        free      shared  buff/cache   available
Mem:         3972748     2342968      479208       68124     1459408     1629780
Swap:        4071420           0     4071420
```

**Comment by orblazer** [comment]
Hello,
This is normal because your swap used is to 0. In this widget the swap have special behavior and is show label only if value is greater then 0.
