### ISSUE TITLE
[BUG] Network monitor not working (Kubuntu 22.04)

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [orblazer/plasma-applet-resources-monitor#9]
**Describe the bug**
I put this applet in my top panel and i was just copying my music library over ssh and noticed it showed 0 activity
look at the settings, set the correct device name, still nothing set to to all and still nothing

**To Reproduce**
Configure applet/widget to show network activity and see nothing

**Expected behavior**
See activity of network

**Screenshots**
see attached screencapture
[2021-11-21 14-44-03.mkv.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7576964/2021-11-21.14-44-03.mkv.zip)

**Versions (please complete the following information):**

- Version : 2.2.2-hotfix.1
- KDE Plasma Version : 5.23.3
- KDE Frameworks Version :5.88
- Qt Version : 5.15.2
- Kernel Version : 5.15.4 (mainline)
- OS Type : 64-bit
- Graphics Platform :  X11

**Additional context**

**Comment by orblazer** [comment]
Hello,
Could you try to set the network sensor to blank for real match `all` (i need to make an fix for allow that).

Thanks

**Comment by GM-Script-Writer-62850** [comment]
when i set it to blank i get a `enp3s0` in the field, this just shows 0KB/s for both up/down, as i  showed using enp42s0 does not work any better than blank
```
$ ifconfig 
enp42s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.145  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::44a0:c100:cdf2:2b1b  prefixlen 64  scopeid 0x20<link>
        ether d8:bb:c1:11:96:e0  txqueuelen 1000  (Ethernet)
        RX packets 695  bytes 728000 (728.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 617  bytes 65339 (65.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 145  bytes 13234 (13.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 145  bytes 13234 (13.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp41s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 3c:9c:0f:80:a1:74  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
$ ip address show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp42s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether d8:bb:c1:11:96:e0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.145/24 brd 10.0.0.255 scope global dynamic noprefixroute enp42s0
       valid_lft 86150sec preferred_lft 86150sec
    inet6 fe80::44a0:c100:cdf2:2b1b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp41s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 3c:9c:0f:80:a1:74 brd ff:ff:ff:ff:ff:ff
```

**Comment by GM-Script-Writer-62850** [comment]
is there more info i can get for you figure out the issue, there is not some dependency that could be missing is there?

**Comment by orblazer** [comment]
No, i just need investigate why that doesn't work, i think that come from here https://github.com/orblazer/plasma-applet-resources-monitor/blob/d6c27ffa495cb701499d471512a6d357bc736516/package/contents/ui/main.qml#L218 .

I go work on it today or tomorrow.

**Comment by GM-Script-Writer-62850** [comment]
Unable to reproduce this using blank on my other system, maybe cause the other system has a 2.5G lan?

Unaffected
```
24:00.0 Ethernet controller: Intel Corporation 82572EI Gigabit Ethernet Controller (Copper) (rev 06)
        Subsystem: Intel Corporation PRO/1000 PT Server Adapter
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 43
        IOMMU group: 17
        Region 0: Memory at fca40000 (32-bit, non-prefetchable) [size=128K]
        Region 1: Memory at fca20000 (32-bit, non-prefetchable) [size=128K]
        Region 2: I/O ports at f000 [size=32]
        Expansion ROM at fca00000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: e1000e
        Kernel modules: e1000e
```
affected
```
2a:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 04)
        Subsystem: Micro-Star International Co., Ltd. [MSI] RTL8125 2.5GbE Controller
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 32
        IOMMU group: 6
        Region 0: I/O ports at f000 [size=256]
        Region 2: Memory at fcd00000 (64-bit, non-prefetchable) [size=64K]
        Region 4: Memory at fcd10000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: r8169
        Kernel modules: r8169
```

**Comment by orblazer** [comment]
That doesn't make sense, if KDE could see the usage.

For know could you list the sensors with bellow step (for have the right values and i don't know other way) :
1. clone the repo
2. Add `console.log(source)` after that line https://github.com/orblazer/plasma-applet-resources-monitor/blob/d6c27ffa495cb701499d471512a6d357bc736516/package/contents/ui/main.qml#L198
3. Run `scripts/test.sh`
4. Share the logs

Thanks.

**Comment by GM-Script-Writer-62850** [comment]
wait a min you really use the same debug call as in a web browser...
guess i will add a few calls
```
qml: 0
qml: needConnect (line 245) true
qml: needConnect (line 245) false
qml: needConnect (line 245) false
qml: needConnect (line 245) false
qml: needConnect (line 245) false
qml: needConnect (line 245) false
qml: Requested info network/interfaces/enp42s0/receiver/data
qml: match (line 233): [network/interfaces/enp42s0/receiver/data,receiver]
qml: needConnect (line 245) true
qml: Requested info network/interfaces/enp42s0/transmitter/data
qml: match (line 233): [network/interfaces/enp42s0/transmitter/data,transmitter]
qml: needConnect (line 245) true
qml: Requested info network/interfaces/wlp41s0/receiver/data
qml: match (line 233): [network/interfaces/wlp41s0/receiver/data,receiver]
qml: needConnect (line 245) true
qml: Requested info network/interfaces/wlp41s0/transmitter/data
qml: match (line 233): [network/interfaces/wlp41s0/transmitter/data,transmitter]
qml: needConnect (line 245) true
qml: needConnect (line 245) false

```

**Comment by GM-Script-Writer-62850** [comment]
I think i found the issue, the data is being replaced not combined with the wifi card's data rate

that said for some reason I can't get the line graph working, only numbers work in the panel, while it works fine on the other system

https://i.imgur.com/HWXnK7O.png (i do not think that is working as intended, but progress is progress)

I tested this by disabling the wifi card in the bios

**Comment by orblazer** [comment]
Oh, thanks.
I have never try with multiple NIC so that explain why i have this issue.

That its great idea for manage speed ! 👍 

Thanks and i go work on ASAP !

**Comment by GM-Script-Writer-62850** [comment]
Now that works so much better, nice job and that looks like it was a lot more work than I expected it to be

I have not restarted since updating on one system yet but i think i found something unintended that could be made into a feature. Without restarting the widget the I/O on the widget (in the measured reading) is still in MB/s and KB/s, you could make doing that a option (at the very least it may help more people know that `Mbps != MBps`)

* Some may prefer to read in MBps and KBps as this is what browsers show download speed in (i am indifferent here)

While I have not restarted it yet but on my system with 1 NIC if I check the interface it will not be checked if I close settings and go back in it remains unchecked

**Comment by orblazer** [comment]
No that was not an big work for support `Kbps` but i have refactor my codes with better components for the features ;)

Since `2.3.0` we can choose between `Kbps` and `KiB/s` but that could be and improvement to add also `KBps` yes.

For your issues if i have understand  :
 - When we switch the mode, its not updated without restart
 - When you have uncked interfaces, you couldn't check it again

**Comment by GM-Script-Writer-62850** [comment]
when i said without restart i mean updated to the new one  with without restating the widget

keep in mind i still have not restarted the widget at this time since updating to the new version, buy if i check my single NIC apply and re open the config until it is unchecked, not a issue with multiple NICs (at least after restarting the widget after the update)

* system with single NIC has not been restarted
* system with 2 NICs has been restarted (updated then rebooted to change BIOS settings to see if it worked now)
   * not that rare to see a system with a Wifi and a Wired NIC, my other system has 2 wired NICs, i just have the onboard one disabled in BIOS (i know my Intel NIC is reliable (retired server hardware) and i do not want to bother finding out how reliable the onboard Realtek 8111H one is)
      * originally got that NIC case my onbaord NIC on my old motherboard did not support WOL in linux (that was a windows only feature)

There are a few things that could be polished a bit more like when you switch from MB/s to Mbps the value converts to the equivalent speed (probably should only do this if the value is in the list of speed choices, if it is not the user probably forget to change units before inputting the number) and the auto formatting while typing numbers as a custom speed is still not great

The Option to show the graph speed units should be on the General tab under charts IMO 
* [ X ] Show network monitor [ X ] Throughput in MB/s

**Comment by GM-Script-Writer-62850** [comment]
note that after the widget is restarted the checkbox settings checkboxes hold

**Comment by GM-Script-Writer-62850** [comment]
[config.zip](https://github.com/orblazer/plasma-applet-resources-monitor/files/7655134/config.zip)
patch: Move network speed setting in general page

figure i am bad at explaining it

**Comment by GM-Script-Writer-62850** [comment]
config -> data -> network
set receive/send speed to 1Gbps (selected menu)
apply
general -> back to data -> network
custom  1000.448

set to 1000.000
apply

leave and come back
1000.448
